PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aama: <http://oi.uchicago.edu/aama/schema/2010#>
PREFIX aamas:	 <http://id.oi.uchicago.edu/aama/2013/schema/>
PREFIX aamag:	 <http://oi.uchicago.edu/aama/2013/graph/>
#PREFIX %abbrev%: <http://id.oi.uchicago.edu/aama/2013/%lang%/>

SELECT DISTINCT  ?val
WHERE {
	?s ?p ?o .
	#aamas:lang  ?language .
	#?language rdfs:label ?lang .
   ?p rdfs:label ?prop .
   ?o rdfs:label ?val .
 	FILTER (?p NOT IN ( aamas:lang ) )
 	#FILTER (?p NOT IN ( aamas:lang, %abbrev%:gender, %abbrev%:number, %abbrev%:person, %abbrev%:pos, %abbrev%:token, rdf:type, %abbrev%:multiLex ) )
}
ORDER BY  ASC(?val)
